# Recipe for adding GTSAM 4.1.1 to a custom Yocto layer
# Modified from the original 4.2.0-5 recipe in meta-ros/meta-ros2-rolling to include older source code reference
# Original - https://github.com/ros/meta-ros/blob/kirkstone/meta-ros2-rolling/generated-recipes/gtsam/gtsam_4.2.0-5.bb

# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_rolling
inherit ros_superflore_generated

DESCRIPTION = "gtsam"
AUTHOR = "Frank Dellaert <gtsam@lists.gatech.edu>"
HOMEPAGE = "https://wiki.ros.org"
SECTION = "devel"
LICENSE = "BSD"
# modified LIC_FILES_CHKSUM to match the license file
LIC_FILES_CHKSUM = "file://package.xml;;md5=5823b0e0fcca3cf5f2a01eeeb3261d47"

ROS_CN = "gtsam"
ROS_BPN = "gtsam"

# replaced tbb with gcc-runtime
ROS_BUILD_DEPENDS = " \
    boost \
    libeigen \
    gcc-runtime \
"

ROS_BUILDTOOL_DEPENDS = " \
    cmake-native \
"

ROS_EXPORT_DEPENDS = ""

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

ROS_EXEC_DEPENDS = ""

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = ""

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
# Bitbake doesn't support the "export" concept, so build them as if we needed them to build this package (even though we actually
# don't) so that they're guaranteed to have been staged should this package appear in another's DEPENDS.
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# CMake build options for GTSAM
EXTRA_OECMAKE = "\
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_VERBOSE_MAKEFILE=ON \
    -DGTSAM_USE_SYSTEM_EIGEN=ON \
    -DGTSAM_BUILD_WITH_MARCH_NATIVE=OFF \
    -DGTSAM_BUILD_UNSTABLE=ON \
    -DGTSAM_BUILD_TESTS=ON \
"

# Additional compiler and linker flags:
CXXFLAGS += "-I${STAGING_DIR_TARGET}/usr/include/c++"
LDFLAGS += "-L${STAGING_DIR_TARGET}/usr/lib"

# Define the source code location and its checksum for verification.
SRC_URI = "https://github.com/borglab/gtsam/archive/refs/tags/4.1.1.tar.gz"
SRC_URI[sha256sum] = "c7b5e6cdad52b141c272778f47baf628975457be3e26ed96a7bc2ae685a00af0"
S = "${WORKDIR}/gtsam-4.1.1"

ROS_BUILD_TYPE = "cmake"

inherit ros_${ROS_BUILD_TYPE}

# Resolves breaking QA check not necessary for this package.
INSANE_SKIP:${PN} += "dev-so"
